### ISSUE TITLE
minor tweak on naming convention description

### ISSUE THREAD

**Issue by aurmer** [oakmac/snowflake-css#12]
Snowflake CSS uses the following convention for class names:

1. only lower-case letters with hyphens (ie: snake-case)
1. append a hyphen and 5-digit hash to the end of the class name:

(added "hyphen and") on second rule.

**Comment by oakmac** [comment]
I think [commit #22272319](https://github.com/oakmac/snowflake-css/commit/222723195419b8d87e0b53ff7f7c671166500e4f) brings some clarity here.

Not sure "hyphen and" is necessary; the examples directly below in the `README` demonstrate the usage.
