### ISSUE TITLE
report needs to return valid JSON

### ISSUE THREAD

**Issue by aurmer** [oakmac/snowflake-css#13]
JSON.parse() doesn't have an error callback, so I either have to trust the result is JSON or I have to put it in a try-catch.

Please format error messages, i.e. `<css input> "Unknown word"` so they can be parsed as JSON.

**Comment by oakmac** [comment]
> so I either have to trust the result is JSON or I have to put it in a try-catch.

In general, it is always good practice to wrap `JSON.parse()` in a `try`/`catch` block. You never know when to trust data that comes from "outside" your program.

That being said, `npx snowflake-css report` should always return valid JSON. And if it is not, then that is a bug in this package.

Do you have an example that generates invalid JSON?

**Comment by aurmer** [comment]
When any error occurs, the stdout I receive is the empty string value.

When I submitted this, I was jumping the gun. I thought the output on my console was stdout.. it was stderr.

So now I am only attempting a parse of stdout if its length is >1
