### ISSUE TITLE
Update vocab. from "hash" to "token"

### ISSUE THREAD

**Issue by pxninja** [oakmac/snowflake-css#20]
**Problem**
Flakes are referenced as a hash, implying class name and or properties influence the the output flake. As I understand it, a flake is created independently of class input, leading to a linguistic disconnect between the term "hash" and the nature of a flake.

**Consider ...**
Reframing the vocabulary to more accurately reflect the nature of a flake alleviates this confusion. One example would be to use the term "token" instead of "hash".

**Comment by oakmac** [comment]
related: Issue #14

Thank you for making this issue. I updated the `README` to clarify the verbiage and removed the use of the term "hash". The 5 random characters at the end of a **flake** are called a **hextail** now.
